#This program asks user to guess a number and continue to prompt user until user gets the number right
    #Will let user know if the number is too high or too low
    #Number will be generated by program betwen 0 and 100
#Author: Sarah Fitzgerald

import random

number = random.randint(1, 100) 

guess = int(input("Please guess the number: "))

while guess != number:
        if number > guess:
            print ("Too low")
        elif number < guess:
            print ("Too high")
        guess = int(input("Please guess again: "))

print ("Well done! Yes the number was", number)